### ISSUE TITLE
Not showing "Stronghold", "Nether Fortress" markers on dynmap

### ISSUE THREAD

**Issue by Karsei** [KovuTheHusky/dynmap-structures#12]
When I visited to the Dynmap in the browser, other markers(Village, Monument, ...) was visible but not visible on the map for some markers. In particular, Fortress in Nether is not displayed at all. markers are set to be visible in config.yml, except for Mineshaft.

And the following errors appeared.

> [18:46:42] [Thread-16/INFO]: [dynmap-structures] Updating markers for world 'world'.
[18:46:42] [Thread-16/INFO]: [dynmap-structures] Updating: Stronghold.dat
[18:46:42] [Thread-16/WARN]: java.io.EOFException: Unexpected end of ZLIB input stream
[18:46:42] [Thread-16/WARN]: 	at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source)
[18:46:42] [Thread-16/WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source)
[18:46:42] [Thread-16/WARN]: 	at java.base/java.util.zip.GZIPInputStream.read(Unknown Source)
[18:46:42] [Thread-16/WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source)
[18:46:42] [Thread-16/WARN]: 	at java.base/java.io.DataInputStream.readByte(Unknown Source)
[18:46:42] [Thread-16/WARN]: 	at com.codeski.nbt.NBTReader.readTag(NBTReader.java:113)
[18:46:42] [Thread-16/WARN]: 	at com.codeski.nbt.NBTReader.read(NBTReader.java:36)
[18:46:42] [Thread-16/WARN]: 	at com.codeski.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.update(DynmapStructuresPlugin.java:94)
[18:46:42] [Thread-16/WARN]: 	at com.codeski.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:70)
[18:46:42] [Thread-16/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

> [20:52:52] [Thread-17/INFO]: [dynmap-structures] Updating markers for world 'world_nether'.
[20:52:52] [Thread-17/INFO]: [dynmap-structures] Updating: Fortress.dat
[20:52:52] [Thread-17/WARN]: java.io.EOFException: Unexpected end of ZLIB input stream
[20:52:52] [Thread-17/WARN]: 	at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source)
[20:52:52] [Thread-17/WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source)
[20:52:52] [Thread-17/WARN]: 	at java.base/java.util.zip.GZIPInputStream.read(Unknown Source)
[20:52:52] [Thread-17/WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source)
[20:52:52] [Thread-17/WARN]: 	at java.base/java.io.DataInputStream.readByte(Unknown Source)
[20:52:52] [Thread-17/WARN]: 	at com.codeski.nbt.NBTReader.readTag(NBTReader.java:113)
[20:52:52] [Thread-17/WARN]: 	at com.codeski.nbt.NBTReader.read(NBTReader.java:36)
[20:52:52] [Thread-17/WARN]: 	at com.codeski.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.update(DynmapStructuresPlugin.java:94)
[20:52:52] [Thread-17/WARN]: 	at com.codeski.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:70)
[20:52:52] [Thread-17/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

## Steps to Reproduce the Problem

  1. Seed is -4892650282755438409.
  2. Sample files are [Fortress.dat](https://mega.nz/#!uaQGkJYS!5w228jP58zjV_qV-36Y5a4_Dh38LBM3kkI_cgJfrZVo), [Stronghold.dat](https://mega.nz/#!mGQzCKzB!TNkB_6_wmcfVRIcLTEpc4qco7iZUnCQfkd8nN4nEWa0)
  3. [dynmap Image](https://imgur.com/a/IX1sRhg)

## Specifications

  - dynmap-structures: 1.4.0
  - dynmap: 2.5-Dev201706100401
  - Bukkit/Spigot: 1.12.2
  - Java: 1.8.0_171
  - System: Linux (CentOS 7), Windows 10

**Comment by KovuTheHusky** [comment]
As far as Nether Fortresses go, the latest snapshot of dynmap-structures may fix that. Do me a favor and try the latest snapshot available on this page:

https://kovuthehusky.com/jenkins/job/dynmap-structures/

If I had to guess, it will fix Nether Fortresses - not sure about the unexpected EOF for Strongholds though. I'll look into that myself and see if I can get the same issue.

If you're curious why I haven't released 1.4.1 with the Nether Fortresses fix (and addition of End Cities and other stuff) I've been waiting for Minecraft 1.13 to make sure dynmap-structures 1.4.1 is compatible with it but Mojang is taking much longer than I expected. I may just release 1.4.1 now and push a quick patch if I need to for 1.13.

**Comment by KovuTheHusky** [comment]
Glad things are working on the snapshot. Expect a release soon, but until then the snapshot should work perfectly fine.
