### ISSUE TITLE
New Warnings with Java 11

### ISSUE THREAD

**Issue by axipher** [KovuTheHusky/dynmap-structures#25]
**Describe the bug**
Getting Warnings after Upgrading to Java

**To Reproduce**
1. Upgrade to Java 11

**Expected behavior**
Expected no Warnings

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04.3
 - Java 11 OpenJDK
 - Paper #650 (MC: 1.13.2)
 - dynmap 3.0-beta5
 - dynmap-structures [e.g. 2.0.0, 2.2.0]

**Additional context**
After a recent upgrade on my server from Java 8 to Java 11, I am getting the following Warnings on server startup.  Dynmap-structures still loads and displays structures correctly.

````
[12:43:22] [Thread-1709/WARN]: Exception in thread "Thread-1709" java.util.ConcurrentModificationException
[12:43:22] [Thread-1709/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[12:43:22] [Thread-1709/WARN]: 	at net.minecraft.server.v1_13_R2.WorldChunkManagerHell.a(SourceFile:50)
[12:43:22] [Thread-1709/WARN]: 	at net.minecraft.server.v1_13_R2.StructureGenerator.getNearestGeneratedFeature(StructureGenerator.java:105)
[12:43:22] [Thread-1709/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.findNearestMapFeature(ChunkGeneratorAbstract.java:60)
[12:43:22] [Thread-1709/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.findNearestMapFeature(NormalChunkGenerator.java:44)
[12:43:22] [Thread-1709/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.locateNearestStructure(CraftWorld.java:1850)
[12:43:22] [Thread-1709/WARN]: 	at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:237)
[12:43:22] [Thread-1709/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[12:43:24] [Thread-3388/WARN]: Exception in thread "Thread-3388" java.util.ConcurrentModificationException
[12:43:24] [Thread-3388/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[12:43:24] [Thread-3388/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.getStructureStartCache(ChunkGeneratorAbstract.java:144)
[12:43:24] [Thread-3388/WARN]: 	at net.minecraft.server.v1_13_R2.StructureGenerator.a(StructureGenerator.java:199)
[12:43:24] [Thread-3388/WARN]: 	at net.minecraft.server.v1_13_R2.StructureGenerator.getNearestGeneratedFeature(StructureGenerator.java:126)
[12:43:24] [Thread-3388/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.findNearestMapFeature(ChunkGeneratorAbstract.java:60)
[12:43:24] [Thread-3388/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.findNearestMapFeature(NormalChunkGenerator.java:44)
[12:43:24] [Thread-3388/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.locateNearestStructure(CraftWorld.java:1850)
[12:43:24] [Thread-3388/WARN]: 	at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:237)
[12:43:24] [Thread-3388/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[12:43:24] [Thread-3390/WARN]: Exception in thread "Thread-3390" java.util.ConcurrentModificationException
[12:43:24] [Thread-3390/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[12:43:24] [Thread-3390/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.getStructureStartCache(ChunkGeneratorAbstract.java:144)
[12:43:24] [Thread-3390/WARN]: 	at net.minecraft.server.v1_13_R2.StructureGenerator.a(StructureGenerator.java:199)
[12:43:24] [Thread-3390/WARN]: 	at net.minecraft.server.v1_13_R2.StructureGenerator.getNearestGeneratedFeature(StructureGenerator.java:126)
[12:43:24] [Thread-3390/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.findNearestMapFeature(ChunkGeneratorAbstract.java:60)
[12:43:24] [Thread-3390/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.findNearestMapFeature(NormalChunkGenerator.java:44)
[12:43:24] [Thread-3390/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.locateNearestStructure(CraftWorld.java:1850)
[12:43:24] [Thread-3390/WARN]: 	at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:237)
[12:43:24] [Thread-3390/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[12:43:25] [Thread-1706/WARN]: Exception in thread "Thread-1706" java.util.ConcurrentModificationException
[12:43:25] [Thread-1706/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[12:43:25] [Thread-1706/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.getStructureStartCache(ChunkGeneratorAbstract.java:144)
[12:43:25] [Thread-1706/WARN]: 	at net.minecraft.server.v1_13_R2.StructureGenerator.a(StructureGenerator.java:199)
[12:43:25] [Thread-1706/WARN]: 	at net.minecraft.server.v1_13_R2.StructureGenerator.getNearestGeneratedFeature(StructureGenerator.java:126)
[12:43:25] [Thread-1706/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.findNearestMapFeature(ChunkGeneratorAbstract.java:60)
[12:43:25] [Thread-1706/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.findNearestMapFeature(NormalChunkGenerator.java:44)
[12:43:25] [Thread-1706/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.locateNearestStructure(CraftWorld.java:1850)
[12:43:25] [Thread-1706/WARN]: 	at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:237)
[12:43:25] [Thread-1706/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[12:43:25] [Thread-1681/WARN]: Exception in thread "Thread-1681" java.util.ConcurrentModificationException
[12:43:25] [Thread-1681/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[12:43:25] [Thread-1681/WARN]: 	at net.minecraft.server.v1_13_R2.WorldChunkManagerOverworld.a(SourceFile:197)
[12:43:25] [Thread-1681/WARN]: 	at net.minecraft.server.v1_13_R2.StructureGenerator.getNearestGeneratedFeature(StructureGenerator.java:105)
[12:43:25] [Thread-1681/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.findNearestMapFeature(ChunkGeneratorAbstract.java:60)
[12:43:25] [Thread-1681/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.findNearestMapFeature(NormalChunkGenerator.java:44)
[12:43:25] [Thread-1681/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.locateNearestStructure(CraftWorld.java:1850)
[12:43:25] [Thread-1681/WARN]: 	at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:237)
[12:43:25] [Thread-1681/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
````

**Comment by KovuTheHusky** [comment]
You should now see a single line warning in [2.3.0](https://github.com/KovuTheHusky/dynmap-structures/releases/tag/2.3.0) for this exception. Let me know if you have any issues!
