### ISSUE TITLE
1.19 biomes update?

### ISSUE THREAD

**Issue by solek1312** [KovuTheHusky/dynmap-structures#60]
It doesn't work with 1.19 out of the box, I wonder if it would be hard to update it to support the new biomes.
`java.lang.NullPointerException: Cannot read the array length because "com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.BIOMES[org.bukkit.block.Biome.ordinal()]" is null
        at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.onEnable(DynmapStructuresPlugin.java:538) ~[DynmapStructures-2.5.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-31]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-31]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by KovuTheHusky** [comment]
Will be fixed soon - was on vacation when 1.19 released.
