### ISSUE TITLE
Not loading in 1.20

### ISSUE THREAD

**Issue by glippi-zz** [KovuTheHusky/dynmap-structures#75]
24.06 13:08:00 [Server] Server thread/INFO [dynmap-structures] Enabling dynmap-structures v2.6.0
24.06 13:08:00 [Server] Server thread/ERROR Error occurred while enabling dynmap-structures v2.6.0 (Is it up to date?)
24.06 13:08:00 [Server] INFO java.lang.NullPointerException: Cannot read the array length because "com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.BIOMES[org.bukkit.block.Biome.ordinal()]" is null
24.06 13:08:00 [Server] INFO at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.onEnable(DynmapStructuresPlugin.java:552) ~[?:?]
24.06 13:08:00 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
24.06 13:08:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
24.06 13:08:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
24.06 13:08:00 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
24.06 13:08:00 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
24.06 13:08:00 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
24.06 13:08:00 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
24.06 13:08:00 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
24.06 13:08:00 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
24.06 13:08:00 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
24.06 13:08:00 [Server] INFO at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by glippi-zz** [comment]
Not sure if there is still fixing going on for this part, but currently it is not able to load dynmap-strucutures and gives the above error. Please feel free to let me know if you like more or if this is not going to get fixed as development stopped.

Love the plugin so far, always used it and is great for exploration adventures.

**Comment by JafraOnline** [comment]
Yes, I have the same problem with 1.20.1. Hopefully the developer will fix it. It is be a great addon for DynMap.

**Comment by diebasis** [comment]
Hello.
I have the same problem reported above.
However, I am using PaperMC version 1.19.4.
I downloaded the source code, recompiled it in IntelliJ and there were no problems generating the JAR.
But it shows the same error messages in the console when trying to load the plugin.
Any tips on what can be done?

An addendum... this error does not occur in version 1.19.2, only from 1.19.4 onwards.

**Comment by AmonBune** [comment]
@KovuTheHusky Please review the PR #77 since this issue prevents people from being able to load the plugin in all newer server versions.

**Comment by Pezmc** [comment]
I've built a release which can be found at https://github.com/Pezmc/dynmap-structures/releases/tag/2.6.2, which includes #77 and some other dependency updates.
